services:
  audio2text:
    build:
      context: .
      dockerfile: Dockerfile.cn
    container_name: audio2text
    ports:
      - "8000:8000"
    volumes:
      - ./storage:/app/storage
    environment:
      - TZ=Asia/Shanghai
    restart: unless-stopped
